### PR TITLE
Fix build with uClibc

### PR DESCRIPTION
**Pull request by ismaell**

### CODE REVIEW

**Comment by paul99** [comment]
Hi Ismael -

Thanks for the patch!

I'm out of office on vacation, back Monday 19th. I'll forward this to a colleague to merge, but if it slips thru the cracks,please ping me again next week. I'm not too organized here on vacation.

Love to hear how your are using v8!

Thanks again!

Paul

**Comment by ismaell** [comment]
@paul99, I'm kind of bored about the CLA stuff. Never received a reply from
Google, and the change is obviously not copyrightable anyway...

**Comment by paul99** [comment]
Sorry about the CLA. It has worked for us. But what a pain for a small change.

Good news is that we did fix uClibc support, in a slightly different way, but it seems to be fine. It's was committed in this repo with 9ffd37e7a8 on Mar 15, and merged to Google's repo with r 11242 (cfc829f7e) on April 5. 

Sorry that I forgot to notify you.

Please let me know if this change is insufficient for you, otherwise we will close this out.

**Comment by ismaell** [comment]
Of course that works for me.

Thanks.

**Pull request closed without merging**
